KBUILD_CFLAGS += -Wlarger-than=28792
KBUILD_CFLAGS += -Wstack-usage=1856

#Third part codecs
snd-soc-ad83586b-objs := ad83586b.o

#Third part codecs
obj-$(CONFIG_AMLOGIC_SND_SOC_AD83586B) += ad83586b.o
