KBUILD_CFLAGS += -Wlarger-than=28792
KBUILD_CFLAGS += -Wstack-usage=1856

#Third part codecs
snd-soc-du161-objs := du161.o du161-i2c.o

#Third part codecs
obj-$(CONFIG_AMLOGIC_SND_SOC_DU161) += snd-soc-du161.o
