KBUILD_CFLAGS += -Wlarger-than=28792
KBUILD_CFLAGS += -Wstack-usage=1856

#Third part codecs
snd-soc-ad82584f-objs := ad82584f.o

#Third part codecs
obj-$(CONFIG_AMLOGIC_SND_SOC_AD82584F) += ad82584f.o
