# NXP
#obj-y	+= tfa_container.o
#obj-y	+= tfa_dsp.o
#obj-y	+= tfa_init.o
#obj-y	+= tfa98xx.o
snd-soc-tfa98xx-objs := tfa98xx.o tfa_init.o tfa_dsp.o tfa_container.o

obj-$(CONFIG_NXP_SND_CODEC_TFA98XX) += snd-soc-tfa98xx.o


